---
title: "RMBL GCMS Standards"
author: "[John Powers](http://sites.uci.edu/powers/)"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: no
    lib_dir: libs
    code_folding: hide
    toc: yes
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, message=FALSE}
library(tidyverse)
library(reshape2)
library(knitr)
knitr::opts_chunk$set(comment="", cache=T, warning = F, message = F, 
                      fig.path = "images-standards/", dev="svglite", dev.args=list(fix_text_size=FALSE), fig.height=8, fig.width=8)
options(knitr.kable.NA = "")
ggplot2::theme_set(theme_minimal())
```

```{r load_standards}
# source("read_shimadzu.R")
# #grab all the files in the data folder - add new Shimadzu output here and give it 2 digit prefix number
# setwd("~/MyDocs/MEGA/UCI/Schiedea/Analysis/scent/rmbl/Standards/data")
# stds.data <- list.files() %>% set_names() %>% map(read.shimadzu) %>% bind_rows(.id="batch") %>% 
#   filter(!Filename %in% c("Blank_07192019.qgd"))
# setwd("~/MyDocs/MEGA/UCI/RMBL 2020/RMBL-GCMS/")
# save(stds.data, file = "data/standards_data.rda")

load("data/standards_data.rda")

mix <- deframe(read_csv("data/standards_names.csv")) #combine some compound names
mergedmix <- unique(mix)

stds <- stds.data %>% filter(Name %in% names(mix)) %>% 
  mutate(Name = factor(recode(Name, !!!mix), levels=mergedmix)) %>% 
  dcast(Filename~Name, sum, value.var="Area", drop=F) %>% 
  write_csv("output/standards/standards_qual.csv")
#Import standards_qual.csv into https://docs.google.com/spreadsheets/d/1BqdNz8hb_CGbX83Rg8Zr42TPwb4z_JN42Qf_Je4Sz4k/edit#gid=2145192042
#Add metadata: type	notes	rundate	batch	conc	replicate	year
#Then download the metadata tab to /data and read it back in:
stds.meta <- read_csv("data/shimadzu_standards - metadata.csv") %>% select(-all_of(mergedmix)) %>% 
  mutate(datebatch = factor(paste(rundate, batch)),
         yearbatch = factor(paste(year, batch)) %>% fct_reorder(rundate))

meta.mix <- left_join(stds.meta, stds) #joins the metadata and the peak areas
stds <- meta.mix %>% select(Filename, all_of(mergedmix)) %>% #reorder stds to match stds.meta
  column_to_rownames("Filename") 

meta.mix.long <- meta.mix %>% 
  pivot_longer(all_of(mergedmix), names_to="standard", values_to="area") %>% 
  filter(type=="Standards" | 
           (standard == "indole" & type == "Indole") | #indole only
           (standard == "a-pinene" & type=="PineneOctanone"), #special mix with just these two
         !(standard=="benzaldehyde" & year(rundate) > 2018),
         !(standard=="a-farnesol" & year(rundate) > 2019),#stopped using these standards
         !(standard=="a-farnesene" & year(rundate) < 2021),#started using this standard instead
         !(standard == "methyl 2-hydroxybenzoate" & batch=="2021fresh"), #forgot to add standard
         !(standard == "indole" & batch=="freshstds_noindole"), #did not add standard
         is.na(exclude)) #manually drop particular files - see notes

#TODO look at the rest of these exclusions
# batches_sans_stds <- c("2018 leak", "newxfer_leak",  "Diane", "2019fresh","2018old", "Warmup")
# batches_sans_indole <- c(batches_sans_stds, "freshstds_noindole")
# datebatches_sans_stds <- c("2018-09-03 2018 no leak")
# datebatches_sans_indole <- c(datebatches_sans_stds, "2019-06-21 2018fresh", "2017-06-30 2017 good")
#TODO check excluded peak areas in "rmbl/Standards/metadata/regressions_2019_prexfer_filtered.csv"
```

# Inventory

```{r inventory}
stds.meta %>% count(year, type) %>% pivot_wider(names_from="type", values_from="n") %>% 
  kable(caption="chromatograms in each year by type")
#3Standards and 4Standards are mixes with low peak areas, not sure which standards they contain

stds.meta %>% filter(!type %in% c("Alkanes","Blank")) %>% count(year, batch, rundate) %>% 
  kable(caption="chromatograms in each batch (excl. alkanes and blanks)") 
```

# Peak areas

```{r plot_areas}
walk(mergedmix, function(chem) {
  meta.mix.long %>% filter(standard==chem) %>% 
    ggplot(aes(x=fct_rev(factor(paste(rundate, year, batch))), y=area, color=log10(conc)))  + 
    geom_point(size=2) + geom_line(aes(group=conc)) + coord_flip()+
    scale_y_log10() + scale_color_gradient(low="purple",high="orange") +
    labs(title=chem, x="Batch", y="Area") + theme(axis.text.y = element_text(hjust=0)) 
  ggsave(filename=paste0("output/standards/area/area_",chem,".svg"), width=8, height=6)
})
```


# Regressions

Regressions are plotted in output/standards/regressions

```{r plot_regressions}
walk(mergedmix, function(chem) {
  meta.mix.long %>% filter(standard==chem) %>% 
    ggplot(aes(x=conc, group=datebatch, color=year, y=area)) +
    scale_x_log10("Concentration (mg/mL)") + scale_y_log10("Area") + #ignores zeros
    stat_smooth(method="lm", formula = y~x, se=F, geom="line", alpha=1, size=1) + 
    geom_point(pch=24, size=2) + 
    scale_color_brewer("Year", palette="Set3", type="qual") + ggtitle(chem)
  ggsave(filename=paste0("output/standards/regressions/regression_",chem,".svg"), width=8, height=6)
})
```

```{r run_regressions}
slopes <- meta.mix.long %>% 
  mutate(mass_ng = conc * 3 * 1000) %>% # concentration in ug/uL * 3 uL * 1000 ng/ug = mass of standard pipetted in ng
  group_by(year, yearbatch, batch, type, standard) %>% nest() %>% 
  mutate(model = map(data, ~ lm(area ~ mass_ng + 0, data=.x)), #force through zero (no intercept)
         area_per_ng = map_dbl(model, coef),
         ng_per_area = (1/map_dbl(model, coef)),
         r2 = map_dbl(model, ~ summary(.x)$r.squared),
         n = map_int(data, nrow)) %>% 
  select(-data, -model) %>% 
  write_csv("output/standards/regression_slopes.csv")

# ggplot(slopes, aes(x= fct_rev(yearbatch), y = area_per_ng, color=r2)) + facet_wrap(vars(standard), scales="free_x") +
#   geom_line(aes(group=standard), color="black") + geom_point(aes(size=n)) + coord_flip() + 
#   theme(axis.text.y = element_text(hjust=0)) + labs(y="Area/ng", x="Batch")

ggplot(slopes, aes(x= fct_rev(yearbatch), y = area_per_ng, color=standard)) + 
  geom_line(aes(group=standard), color="black") + geom_point(aes(size=n)) + coord_flip() + 
  theme(axis.text.y = element_text(hjust=0)) + labs(y="Area/ng", x="Batch") +
  scale_color_brewer(palette = "Set1") + scale_y_sqrt()
```

# Alkanes

```{r alkanes}
alkanes <- read_csv("data/alkanes.csv") %>% select(-RT_kmeans)

alk.data.name <- alkanes %>% left_join(stds.data, join_by(Name)) %>% select(-Synonyms) %>% 
  filter(str_detect(Filename, "Alk|ALK"), Ret.Time > 2, Ret.Time < 19.5) %>% #C6-C18
  mutate(gc_method = str_extract(Filename,"Adams|Tendeg") %>% replace_na("Ipo")) %>% filter(gc_method=="Ipo") %>% 
  mutate(date = Filename %>% str_extract("[0-9]+20[0-9]+") %>% str_replace("^([1-9]+)","0\\1") %>% mdy(),
         n.kmean = kmeans(Ret.Time, centers = alkanes %>% filter(n>=6, n<=18) %>% pull(RT_2022))$cluster + 5)

alkanes <- alkanes %>% select(-any_of("RT_kmeans")) %>% 
  left_join(alk.data.name %>% group_by(n.kmean) %>% summarize(RT_kmeans = median(Ret.Time)), join_by(n==n.kmean)) %>% 
  write_csv("data/alkanes.csv")
get_kovats <- with(alkanes, approxfun(x = RT_kmeans, y = n * 100)) #Linear interpolation
save(alkanes, get_kovats, file="output/get_kovats.rda")

alk.data <- alk.data.name %>% select(-any_of(colnames(alkanes))) %>% left_join(alkanes, join_by(n.kmean==n)) 

ggplot(alk.data, aes(x=Ret.Time, y=Filename)) + 
  geom_rug(sides="b") + geom_text(aes(label=n.kmean, color=factor(n.kmean))) +
  scale_x_continuous(breaks=alkanes$n, minor_breaks = NULL) + guides(color="none")

ggplot(alk.data %>% rename(n=n.kmean), aes(x=Ret.Time, color=as.character(n), y=Area)) + 
  geom_vline(data=alkanes, aes(xintercept=RT_kmeans)) + 
  geom_text(data=alkanes, aes(x=RT_kmeans, y=2e8, label=n))+
  geom_point(data=alkanes, aes(x=RT_2022, y = 1e8))  +
  geom_path(aes(group=Filename)) + geom_point(size=2) + geom_rug(sides="b") +
  scale_y_sqrt() + guides(color="none")

alk.data %>% mutate(RT_offset = Ret.Time - RT_2022,
                    Filename = fct_reorder(Filename, -RT_offset, .fun=median)) %>% 
  ggplot(aes(x=n.kmean, y=RT_offset, color=factor(date))) +
  geom_line(aes(group=Filename)) + geom_point(aes(size=Area)) + 
  scale_x_continuous(breaks=alkanes$n, minor_breaks = NULL)

ggplot(alk.data, aes(x=n.kmean, y=Ret.Time, color=factor(date))) + 
  geom_line(size=0.3) + geom_line(data=drop_na(alkanes, RT_2022), aes(x=n, y=RT_2022), color="black") + geom_point() +
  scale_x_continuous(breaks=alkanes$n, minor_breaks = NULL) 

#See if there are misidentified alkane peaks - not many
# alk.data.all <- stds.data %>% filter(str_detect(Filename, "Alk|ALK"), !str_detect(Filename,"Adams|Tendeg"), 
#                                      Ret.Time > 2, Ret.Time < 19.5, Height > 8e5)
# 
# ggplot(alk.data.all, aes(x=Ret.Time, y=Height, color=Filename, 
#                          shape=ifelse(Name %in% alkanes$Name, "Alkane", 
#                                       ifelse(Name=="", "No ID","Not alkane")))) +
#   geom_point() + geom_line() + geom_rug(sides="b") + geom_text(aes(label=Name)) + 
#   scale_x_continuous(breaks=1:26) +  scale_shape_manual("Alkane", values=c(19,4,1)) + scale_y_sqrt()
# 
# alk.data.all %>% count(Name) %>% filter(!Name %in% alkanes$Name, n>1) %>% arrange(desc(n))
```

